question_data = [
    {"text": "A slug's blood is green.", "answer": "True"},
    {"text": "The loudest animal is the African Elephant.", "answer": "False"},
    {"text": "Approximately one quarter of human bones are in the feet.", "answer": "True"},
    {"text": "The total surface area of human lungs is the size of a football pitch.", "answer": "True"},
    {"text": "In West Virginia, USA, if you accidentally hit an animal with your car, you are free to take it home to eat.", "answer": "True"},
    {"text": "In London, UK, if you happen to die in the House of Parliament, you are entitled to a state funeral.", "answer": "False"},
    {"text": "It is illegal to pee in the Ocean in Portugal.", "answer": "True"},
    {"text": "You can lead a cow down stairs but not up stairs.", "answer": "False"},
    {"text": "Google was originally called 'Backrub'.", "answer": "True"},
    {"text": "Buzz Aldrin's mother's maiden name was 'Moon'.", "answer": "True"},
    {"text": "No piece of square dry paper can be folded in half more than 7 times.", "answer": "False"},
    {"text": "A few ounces of chocolate can to kill a small dog.", "answer": "True"},
    {"text": "The capital of Australia is Sydney.", "answer": "False"},
    {"text": "The Great Wall of China is visible from space.", "answer": "False"},
    {"text": "Humans share 50% of their DNA with bananas.", "answer": "True"},
    {"text": "The shortest war in history lasted 38 minutes.", "answer": "True"},
    {"text": "The unicorn is the national animal of Scotland.", "answer": "True"},
    {"text": "Honey never spoils.", "answer": "True"},
    {"text": "Adult humans have fewer bones than babies.", "answer": "True"},
    {"text": "Lightning never strikes the same place twice.", "answer": "False"},
    {"text": "Octopuses have three hearts.", "answer": "True"},
    {"text": "Bananas grow on trees.", "answer": "False"},
    {"text": "The longest river in the world is the Amazon River.", "answer": "False"},
    {"text": "Goldfish have a memory span of three seconds.", "answer": "False"},
    {"text": "The Eiffel Tower can be 15 cm taller during the summer.", "answer": "True"},
    {"text": "There are more stars in the universe than grains of sand on all the world's beaches.", "answer": "True"},
    {"text": "Bulls are attracted to the color red.", "answer": "False"},
    {"text": "An octopus has three hearts.", "answer": "True"},
    {"text": "A sneeze is faster than the blink of an eye.", "answer": "True"},
    {"text": "Penguins can fly.", "answer": "False"},
    {"text": "There are more bones in your hand than in your foot.", "answer": "False"},
    {"text": "Mount Everest is the tallest mountain in the world.", "answer": "False"},
    {"text": "Sharks are mammals.", "answer": "False"},
    {"text": "The human nose can detect over 1 trillion scents.", "answer": "True"},
    {"text": "Hot water freezes faster than cold water.", "answer": "True"},
    {"text": "The moon is slowly moving away from Earth.", "answer": "True"},
    {"text": "Humans can breathe and swallow at the same time.", "answer": "False"},
    {"text": "The Empire State Building is taller than the Eiffel Tower.", "answer": "True"},
    {"text": "Venus is the hottest planet in our solar system.", "answer": "True"},
    {"text": "There are more cells in the human body than stars in the Milky Way.", "answer": "True"},
    {"text": "Sound travels faster in water than in air.", "answer": "True"},
    {"text": "A group of flamingos is called a 'flamboyance'.", "answer": "True"},
    {"text": "The smallest bone in the human body is in the ear.", "answer": "True"},
    {"text": "The capital of Canada is Toronto.", "answer": "False"},
    {"text": "Polar bear fur is actually white.", "answer": "False"},
    {"text": "Humans have more than five senses.", "answer": "True"},
    {"text": "Venus is the closest planet to the Sun.", "answer": "False"},
    {"text": "The heart of a shrimp is located in its head.", "answer": "True"},
    {"text": "An ostrich's eye is bigger than its brain.", "answer": "True"},
    {"text": "A crocodile cannot stick its tongue out.", "answer": "True"},
    {"text": "Butterflies taste with their feet.", "answer": "True"},
    {"text": "New York is the capital of the United States.", "answer": "False"},
    {"text": "Mickey Mouse's first words were 'hot dogs'.", "answer": "True"},
    {"text": "In space, you cannot cry because there is no gravity to make the tears flow.", "answer": "True"},
    {"text": "A crocodile can run faster than a human.", "answer": "False"},
    {"text": "The average human body contains enough sulfur to kill all fleas on an average dog.", "answer": "True"},
    {"text": "Bananas are berries.", "answer": "True"},
    {"text": "The human skeleton renews itself completely every 10 years.", "answer": "True"},
    {"text": "Birds are the only animals that have feathers.", "answer": "True"},
    {"text": "Humans and dinosaurs coexisted.", "answer": "False"},
    {"text": "The longest recorded flight of a chicken is 13 seconds.", "answer": "True"},
    {"text": "Olympic gold medals are made entirely of gold.", "answer": "False"},
    {"text": "There are more trees on Earth than stars in the Milky Way.", "answer": "True"},
    {"text": "The average person walks the equivalent of five times around the world in a lifetime.", "answer": "True"},
    {"text": "The inventor of the Pringles can is buried in one.", "answer": "True"},
    {"text": "Adult cats are lactose intolerant.", "answer": "True"},
    {"text": "Humans can distinguish between over a million different colors.", "answer": "True"},
    {"text": "Alaska is the state with the highest percentage of people who walk to work.", "answer": "True"},
    {"text": "The first computer virus was created in 1986.", "answer": "True"},
    {"text": "The human body contains about 100,000 miles of blood vessels.", "answer": "True"},
    {"text": "A day on Venus is longer than a year on Venus.", "answer": "True"},
    {"text": "Camels have three sets of eyelids.", "answer": "True"},
    {"text": "There are more public libraries in the U.S. than McDonald's restaurants.", "answer": "True"},
    {"text": "The first oranges weren’t orange.", "answer": "True"},
    {"text": "A human's pinky finger contributes to nearly 50% of hand strength.", "answer": "True"},
    {"text": "You can sneeze in your sleep.", "answer": "False"},
    {"text": "The shortest commercial flight in the world lasts just 57 seconds.", "answer": "True"},
    {"text": "The Mona Lisa has no eyebrows.", "answer": "True"},
    {"text": "Carrots were originally purple in color.", "answer": "True"},
    {"text": "The term 'robot' comes from a Czech word that means 'forced labor'.", "answer": "True"},
    {"text": "The longest word in the English language is 45 letters long.", "answer": "True"},
    {"text": "Elephants are the only animals that can't jump.", "answer": "True"},
    {"text": "Chewing gum takes seven years to digest.", "answer": "False"},
    {"text": "There are more fake flamingos in the world than real ones.", "answer": "True"},
    {"text": "The shortest verse in the Bible consists of only two words.", "answer": "True"},
    {"text": "Humans can survive without a brain.", "answer": "False"},
    {"text": "More people are killed annually by cows than by sharks.", "answer": "True"},
    {"text": "Humans have 206 bones in their body at birth.", "answer": "False"},
    {"text": "A snail can sleep for three years.", "answer": "True"},
    {"text": "An electric eel can produce a shock strong enough to start a fire.", "answer": "True"},
    {"text": "You can see the Great Wall of China from the moon.", "answer": "False"},
    {"text": "There are more bacteria in a human mouth than there are people in the world.", "answer": "True"},
    {"text": "A day on Mars is longer than a day on Earth.", "answer": "True"},
    {"text": "Venus is the only planet that rotates clockwise.", "answer": "True"},
    {"text": "Humans are the only animals that blush.", "answer": "True"},
    {"text": "There are more English speakers in China than in the United States.", "answer": "True"},
    {"text": "Human teeth are the only part of the body that cannot heal themselves.", "answer": "True"}
]
